language: node_js
node_js: "stable"
before_install:
  - rvm install 2.4.0
  - rvm use 2.4.0
  - gem install bundler
  - bundle install
  - npm install -g gulp
  - npm install
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
