name: Jason Morris
description: Personal site of Jason Morris
url: ""

twitter: jsnmrs
github: jsnmrs
gravatar_url: http://s.gravatar.com/avatar/1b78531c35d3fa8239f8f7a982260c81

lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:title/
timezone: America/New_York
paginate: 20
paginate_path: ":num"

exclude: [node_modules, Gemfile, Gemfile.lock, Gruntfile.js, package.json, .git, .gitignore, .DS_Store, readme.md]

gems:
- jekyll-redirect-from
- jekyll-sitemap
