name: Jason Morris
description: Personal site of Jason Morris
url: https://jasonmorris.com
enforce_ssl: jasonmorris.com

# Local server settings
port: 4000
host: 127.0.0.1

lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:title/
timezone: America/New_York

feed:
  path: atom.xml

exclude:
  [
    CNAME,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    package-lock.json,
    readme.md,
  ]

plugins:
  - jekyll-feed
  - jekyll-sitemap
