name: Jason Morris
description: Personal site of Jason Morris
url: https://jasonmorris.com
enforce_ssl: jasonmorris.com

twitter: jsnmrs
github: jsnmrs
gravatar_url: http://s.gravatar.com/avatar/1b78531c35d3fa8239f8f7a982260c81

# Local server settings
port: 4000
host: 127.0.0.1

sass:
  sass_dir: _sass
  style: :compressed

lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:title/
timezone: America/New_York
paginate: 20
paginate_path: ":num"

feed:
  path: atom.xml

exclude: [CNAME, Gemfile, Gemfile.lock, node_modules, Gruntfile.js, package.json, readme.md]

gems:
- jekyll-feed
- jekyll-sitemap
