name: Build, test, deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm test
        env:
          CI: true
      - name: Deploy over SSH
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: ${{ secrets.ARGS }}
          SOURCE: "_site/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
  perf:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Webpagetest
        uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
          TEST_URL: https://jasonmorris.com
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
        with:
          args: first="true" video="false" runs="2"
