name: Build and test

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:
  schedule:
    - cron: "03 00 * * 4" # Run every Thursday at 12:03am

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Build site and test
        run: npm test

      # - run: npm run write &

      # - name: Scan site
      #   uses: double-great/accessibility-scan-action@v0.3.0
      #   with:
      #     url: "http://localhost:8080"

      # - name: Upload report as artifact
      #   uses: actions/upload-artifact@v4
      #   if: success() || failure()
      #   with:
      #     name: "Accessibility report"
      #     path: ${{ github.workspace }}/_accessibility-reports/
