name: Build and test

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:
    branches:
      - main
  schedule:
    - cron: "03 00 * * 4" # Run every Thursday at 12:03am

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Build site and test
        run: npm test
      - name: Run Lighthouse on local build
        uses: treosh/lighthouse-ci-action@9.3.0
        with:
          configPath: "./lighthouserc.json"
      - name: Run Accessibility Insights site-wide
        uses: microsoft/accessibility-insights-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          site-dir: ${{ github.workspace }}/_site
      - name: Upload Accessibility Insights report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
