name: Create tagged PDF

on:
  workflow_dispatch: # enable run button on github.com
  push:
    branches:
      - main
    paths:
      - "pages/resume.md"

jobs:
  create:
    name: Create PDF with DocRaptor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Build site and test
        run: npm run write &
      - name: Send to DocRaptor
        run: |
          curl https://${{ secrets.DOCRAPTOR_KEY }}@api.docraptor.com/docs \
              --fail --silent --show-error \
              --header "Content-Type:application/json" \
              --data '{"test": true, \
                  "document_url": "http://localhost:8080/resume/", \
                  "type": "pdf", \
                  "prince_options": { "profile": "PDF/UA-1", "tagged-pdf": true } }' \
                  > resume.pdf
