name: Deploy

on:
  workflow_dispatch: # enable run button on github.com
  push:
    branches:
      - main

env:
  WORK_PATH: "./"
  LOCK_PATH: "./package-lock.json"
  NODE_VERSION: "16"

jobs:
  build-deploy:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ env.NODE_VERSION }}.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ env.LOCK_PATH }}
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORK_PATH }}
      - name: Build site
        run: npm run build
        working-directory: ${{ env.WORK_PATH }}
      - name: Deploy over SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: ${{ secrets.ARGS }}
          SOURCE: "_site/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
