name: Performance

on:
  schedule:
    - cron: "15 6 * * *"

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Webpagetest
        uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_KEY }}
          TEST_URL: https://jasonmorris.com
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
        with:
          args: first="true" video="false" runs="2"
