name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
      - run: npm install
      - run: npm run test
        env:
          CI: true
      - name: Run Lighthouse on local build
        uses: treosh/lighthouse-ci-action@7.0.0
        with:
          # no urls needed, since it uses local folder to scan .html files
          configPath: "./lighthouserc.json"
